### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by thomas-bello** [G100my/G100my.github.io#3]
大佬，请教一下，我参考您的项目自己也配置了一个，但是用的是 ` "vuepress": "^2.0.0-beta.49"， `tailwindcss` 部分的配置有点问题，请问可以帮忙看看吗？

在 `docs/.vuepress/theme/components/Header.vue` 的  `style` 内用 `@apply` 是可以用到 `tailwindcss` 的，但是在 `template` 的 `class` 内就不可以了

可复现仓库 
[https://github.com/thomas-bello/vuepress2-tailwind-starter](https://github.com/thomas-bello/vuepress2-tailwind-starter)

**Comment by G100my** [comment]
您好，新年快樂
這似乎是因為 vuepress 檔案目錄結構是 `.vuepress`、是 `.` 開頭的，所以被系統忽略了。
在 tailwind.config.content 裡面明確指出路徑就可以了。
```
content: ['docs/.vuepress/**/*.vue'],
```

抱歉我的 blog 一直是荒廢狀態，這次過年心血來潮來整理才看到😅
居然過了半年了...
